name: jbr-linux-x64

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Clone Repository
      uses: actions/checkout@v1

    - name: Init Build Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get remove -y --purge azure-cli ghc zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /usr/lib/jvm/
        sudo -E apt-get update -y
        sudo -E apt-get install -y ant autoconf bison build-essential cmake flex git gperf ksh \
            libasound2-dev libavcodec-dev libavformat-dev libcups2-dev libfontconfig1-dev \
            libgl1-mesa-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
            libgtk2.0-dev libgtk-3-dev libjpeg-dev libpng-dev libudev-dev libx11-dev libxext-dev \
            libxml2-dev libxrandr-dev libxrender-dev libxslt1-dev libxt-dev libxtst-dev libxxf86vm-dev \
            make mercurial openjdk-11-jdk pkg-config ruby tree x11proto-core-dev x11proto-xf86vidmode-dev zip
        sudo -E apt-get autoremove -y --purge
        sudo -E apt-get clean -y

    - name: Generate Information
      id: gen_info
      env:
        TZ: Asia/Shanghai
      run: |
        release_tag="$(date +%Y-%m-%d_%H-%M)"
        release_name="jbr-linux-x64-$release_tag"
        release_description="${{ secrets.DESC }}"
        echo "##[set-output name=release_tag;]$release_tag"
        echo "##[set-output name=release_name;]$release_name"
        echo "##[set-output name=release_description;]$release_description"

    - name: Compile JCEF
      env:
        JDK_11: /usr/lib/jvm/java-11-openjdk-amd64
        ANT_HOME: /usr/share/ant
      run: |
        git clone https://github.com/JetBrains/jcef.git jcef
        cd jcef
        git checkout 4ef9139d8abd01b72e29ae33c125d937cd942416
        cd ..
        cd jcef/jb/tools/linux && chmod +x *
        ./build.sh all

    - name: List Paths
      run: |
        cd jcef
        ls -a
        echo
        tree -a

    - name: Patch & Compile JetBrainsRuntime with JCEF
      env:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
        JDK_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      run: |
        git config --global core.autocrlf input
        git clone -b main --single-branch https://github.com/JetBrains/JetBrainsRuntime.git
        cd JetBrainsRuntime
        git checkout jb11_0_15-b2043.56
        mkdir jcef_linux_x64 && tar zxf ../jcef/jcef_linux_x64.tar.gz -C jcef_linux_x64
        git apply -p0 < jb/project/tools/patches/add_jcef_module.patch
        mv ../idea.patch ./
        patch -p1 < idea.patch
        sh ./configure --disable-warnings-as-errors --with-import-modules=./jcef_linux_x64/modular-sdk
        make images

    - name: List Paths
      run: |
        cd JetBrainsRuntime
        ls -a
        echo
        tree -a

    - name: Reduce Size
      env:
        BASE_DIR: build/linux-x86_64-normal-server-release/images
        JBR_BUNDLE: jbr_jcef
        JCEF_PATH: ../jcef/jcef_build/native/Release
      run: |
        cd JetBrainsRuntime
        cat jb/project/tools/common/modules.list > modules_tmp.list
        rm -rf ${BASE_DIR}/${JBR_BUNDLE}
        ${BASE_DIR}/jdk/bin/jlink \
            --module-path ${BASE_DIR}/jdk/jmods --no-man-pages --compress=2 \
            --add-modules $(xargs < modules_tmp.list | sed s/" "//g) --output $BASE_DIR/$JBR_BUNDLE
        cp -R $BASE_DIR/$JBR_BUNDLE $BASE_DIR/jbr
        rsync -av ${JCEF_PATH}/ $BASE_DIR/$JBR_BUNDLE/lib --exclude="modular-sdk"
        grep -v "^JAVA_VERSION" ${BASE_DIR}/jdk/release | grep -v "^MODULES" >> $BASE_DIR/$JBR_BUNDLE/release
        rm -rf ${BASE_DIR}/jbr
        cp -R ${BASE_DIR}/${JBR_BUNDLE} ${BASE_DIR}/jbr

    - name: Package Artifact
      run: |
        cd JetBrainsRuntime/build/linux-x86_64-normal-server-release/images
        zip -r jbr-linux-x64.zip ./jbr/*
        mv jbr-linux-x64.zip ../../../../

    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: ${{ steps.gen_info.outputs.release_tag }}
        path: jbr-linux-x64.zip

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.gen_info.outputs.release_tag }}
        release_name:  ${{ steps.gen_info.outputs.release_name }}
        body: ${{ steps.gen_info.outputs.release_description }}
        draft: false
        prerelease: true

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./jbr-linux-x64.zip
        asset_name: ${{ steps.gen_info.outputs.release_name }}.zip
        asset_content_type: application/zip

